-- =================================================================================
-- POPULAÇÃO DAS TABELAS (INSERTS)
-- =================================================================================

-- 1. Inserção de Leiautes de Arquivo
INSERT INTO public.leiaute_arquivo (
	denominacao
	, tipo_arquivo
	, quantidade_caracteres
	, extensao_arquivo
	, versao_leiaute
) VALUES
	('folha_pagamento_bradesco_240_posicoes', 1, 240, 2, 'VERSÃO 8.0 DE 31/08/2004')
	, ('cobranca_santander_400_posicoes_remessa', 1, 400, 2, 'V 2.37 Fev/2026')
	, ('cobranca_bradesco_400_posicoes_retorno', 2, 400, 1, 'V 2.37 Fev/2026')
	, ('cobranca_santander_400_posicoes_retorno', 2, 400, 1, 'V 2.37 Fev/2026')
	, ('cobranca_sicoob_240_posicoes_retorno', 2, 240, 1, 'V 1.0 DDMMAAAA');

-- 3. Inserção Geral de Campos de Layout
INSERT INTO public.leiaute_campo_arquivo (
	denominacao
	, id_leiaute_arquivo
	, tipo_campo
	, posicao_inicial
	, tamanho
	, tipo_valor
	, preenchimento
	, campo_identificacao
	, valor_padrao
	, expressao_valor
	, nome_coluna
) VALUES
	-- ==============================================
	-- LAYOUT: folha_pagamento_bradesco_240_posicoes
	-- ==============================================
	-- HEADER
	('codigo do banco na compensacao', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 1, 3, 1, NULL, FALSE, '237', NULL, NULL)
	, ('lote de servico', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 4, 4, 1, NULL, FALSE, '0000', NULL, NULL)
	, ('tipo de registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 8, 1, 1, NULL, FALSE, '0', NULL, NULL)
	, ('uso exclusivo febraban', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 9, 9, 2, NULL, FALSE, '         ', NULL, NULL)
	, ('tipo de inscricao da empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 18, 1, 1, NULL, FALSE, '2', NULL, NULL)
	, ('numero de inscricao da empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 19, 14, 1, 3, FALSE, NULL, NULL, NULL)
	, ('codigo do convenio', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 33, 20, 2, 2, TRUE, NULL, NULL, NULL)
	, ('agencia mantenedora da conta', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 53, 5, 1, 3, FALSE, NULL, NULL, NULL)
	, ('digito verificador da agencia', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 58, 1, 2, NULL, FALSE, NULL, NULL, NULL)
	, ('numero da conta corrente', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 59, 12, 1, 3, FALSE, NULL, NULL, NULL)
	, ('digito verificador da conta', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 71, 1, 2, NULL, FALSE, NULL, NULL, NULL)
	, ('digito verificador da agencia conta', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 72, 1, 2, NULL, FALSE, NULL, NULL, NULL)
	, ('nome da empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 73, 30, 2, 2, FALSE, NULL, NULL, NULL)
	, ('nome do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 103, 30, 2, 2, FALSE, 'BANCO BRADESCO                ', NULL, NULL)
	, ('uso exclusivo febraban', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 133, 10, 2, NULL, FALSE, '          ', NULL, NULL)
	, ('arquivo codigo codigo remessa / retorno', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 143, 1, 1, NULL, FALSE, NULL, NULL, NULL)
	, ('data de geracao do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 144, 8, 1, NULL, FALSE, NULL, NULL, NULL)
	, ('hora de geracao do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 152, 6, 1, NULL, FALSE, NULL, NULL, NULL)
	, ('numero sequencial do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 158, 6, 1, 3, FALSE, NULL, NULL, NULL)
	, ('versao do layout do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 164, 3, 1, 3, FALSE, '080', NULL, NULL)
	, ('densidade de gravacao do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 167, 5, 1, 3, FALSE, NULL, NULL, NULL)
	, ('para uso reservado do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 172, 20, 2, NULL, FALSE, '                    ', NULL, NULL)
	, ('para uso reservado da empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 192, 20, 2, NULL, FALSE, '                    ', NULL, NULL)
	, ('uso exclusivo febraban', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 1, 212, 29, 2, NULL, FALSE, '                             ', NULL, NULL)

	-- ==============================================
	-- LAYOUT: cobranca_remessa
	-- ==============================================
	-- HEADER
	, ('Código do Registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 1, 1, 1, NULL, FALSE, '0', NULL, 'codigo_registro')
	, ('Código da Remessa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 2, 1, 1, NULL, FALSE, '1', NULL, 'codigo_remessa')
	, ('Literal de Transmissão', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 3, 7, 2, NULL, FALSE, 'REMESSA', NULL, 'literal_transmissao')
	, ('Código do Tipo Serviço ', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 10, 2, 1, NULL, FALSE, '01', NULL, 'codigo_tipo_servico')
	, ('Literal de Serviço', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 12, 15, 2, NULL, FALSE, 'COBRANCA       ', NULL, 'literal_servico')
	, ('Código de Transmissão', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 27, 20, 1, 4, TRUE, NULL, NULL, 'codigo_transmissao')
	, ('Nome do Beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 47, 30, 2, 2, FALSE, NULL, NULL, 'nome_beneficiario')
	, ('Código do Banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 77, 3, 1, NULL, FALSE, '033', NULL, 'codigo_banco')
	, ('Nome do Banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 80, 15, 2, NULL, FALSE, 'BANCO SANTANDER', NULL, 'nome_banco')
	, ('Data da Gravação do Arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 95, 6, 1, NULL, FALSE, NULL, NULL, 'data_geracao_arquivo')
	, ('Reservado (uso Banco) ', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 101, 16, 1, NULL, FALSE, '0000000000000000', NULL, 'reservado_banco_1')
	, ('Mensagem 1', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 117, 47, 2, 2, FALSE, NULL, NULL, 'mensagem_1')
	, ('Mensagem 2', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 164, 47, 2, 2, FALSE, NULL, NULL, 'mensagem_2')
	, ('Mensagem 3', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 211, 47, 2, 2, FALSE, NULL, NULL, 'mensagem_3')
	, ('Mensagem 4', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 258, 47, 2, 2, FALSE, NULL, NULL, 'mensagem_4')
	, ('Mensagem 5', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 305, 47, 2, 2, FALSE, NULL, NULL, 'mensagem_5')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 352, 34, 2, 2, FALSE, NULL, NULL, 'reservado_banco_2')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 386, 6, 2, 2, FALSE, NULL, NULL, 'reservado_banco_3')
	, ('Nº sequencial do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 392, 3, 1, NULL, FALSE, NULL, NULL, 'numero_sequencial_arquivo')
	, ('Nº sequencial do registro no arquivo ', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 1, 395, 6, 1, 3, FALSE, '000001', NULL, 'numero_sequencial_registro')
	-- MOVIMENTO
	, ('Código do Registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 1, 1, 1, NULL, FALSE, '1', NULL, 'codigo_registro')
	, ('Tipo de inscrição do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 2, 2, 1, NULL, FALSE, NULL, NULL, 'tipo_inscricao_beneficiario')
	, ('Inscrição do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 4, 14, 2, NULL, FALSE, NULL, NULL, 'inscricao_beneficiario')
	, ('Código da agência beneficiária', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 18, 4, 1, NULL, FALSE, NULL, NULL, 'codigo_agencia_beneficiaria')
	, ('Conta movimento beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 22, 8, 1, NULL, FALSE, NULL, NULL, 'conta_movimento_beneficiario')
	, ('Conta cobrança beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 30, 8, 1, NULL, FALSE, NULL, NULL, 'conta_cobranca_beneficiario')
	, ('Identificação do boleto na empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 38, 25, 2, NULL, FALSE, NULL, NULL, 'identificacao_boleto_empresa')
	, ('Identificação do boleto no banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 63, 8, 1, NULL, FALSE, NULL, NULL, 'nosso_numero')
	, ('Data do desconto 2', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 71, 6, 1, NULL, FALSE, NULL, NULL, 'data_desconto_2')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 77, 1, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_1')
	, ('Código de Multa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 78, 1, 1, NULL, FALSE, NULL, NULL, 'codigo_multa')
	, ('Percentual de Multa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 79, 4, 1, NULL, FALSE, NULL, NULL, 'percentual_multa')
	, ('Código da Moeda', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 83, 2, 1, NULL, FALSE, '00', NULL, 'codigo_moeda')
	, ('Valor do boleto em outra unidade', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 85, 13, 1, NULL, FALSE, NULL, NULL, 'valor_boleto_outra_unidade')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 98, 4, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_2')
	, ('Data da Multa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 102, 6, 1, NULL, FALSE, NULL, NULL, 'data_multa')
	, ('Tipo de Cobrança', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 108, 1, 1, NULL, FALSE, NULL, NULL, 'tipo_cobranca')
	, ('Código de movimento remessa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 109, 2, 1, NULL, FALSE, NULL, NULL, 'codigo_movimento_remessa')
	, ('Nº do documento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 111, 10, 2, NULL, FALSE, NULL, NULL, 'numero_documento')
	, ('Data de vencimento do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 121, 6, 1, NULL, FALSE, NULL, NULL, 'data_vencimento_boleto')
	, ('Valor nominal do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 127, 13, 1, NULL, FALSE, NULL, NULL, 'valor_nominal_boleto')
	, ('Número do banco cobrador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 140, 3, 1, NULL, FALSE, '033', NULL, 'numero_banco_cobrador')
	, ('Código agência Cobradora', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 143, 5, 1, NULL, FALSE, NULL, NULL, 'codigo_agencia_cobradora')
	, ('Espécie do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 148, 2, 1, NULL, FALSE, NULL, NULL, 'especie_boleto')
	, ('Identificação boleto aceite / não aceite', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 150, 1, 2, NULL, FALSE, NULL, NULL, 'identificacao_boleto_aceite')
	, ('Data de emissão do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 151, 6, 1, NULL, FALSE, NULL, NULL, 'data_emissao_boleto')
	, ('Primeira instrução', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 157, 2, 1, NULL, FALSE, NULL, NULL, 'primeira_instrucao')
	, ('Segunda instrução', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 159, 2, 1, NULL, FALSE, NULL, NULL, 'segunda_instrucao')
	, ('Valor de Mora dia', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 161, 13, 1, NULL, FALSE, NULL, NULL, 'valor_mora_dia')
	, ('Data Limite para concessão do desconto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 174, 6, 1, NULL, FALSE, NULL, NULL, 'data_limite_desconto')
	, ('Valor do desconto a ser concedido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 180, 13, 1, NULL, FALSE, NULL, NULL, 'valor_desconto')
	, ('Percentual do IOF a ser recolhido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 193, 13, 1, NULL, FALSE, NULL, NULL, 'percentual_iof')
	, ('Valor do abatimento ou Valor do segundo desconto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 206, 13, 1, NULL, FALSE, NULL, NULL, 'valor_abatimento')
	, ('Tipo de inscrição do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 219, 2, 1, NULL, FALSE, NULL, NULL, 'tipo_inscricao_pagador')
	, ('Inscrição do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 221, 14, 2, NULL, FALSE, NULL, NULL, 'inscricao_pagador')
	, ('Nome do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 235, 40, 2, NULL, FALSE, NULL, NULL, 'nome_pagador')
	, ('Endereço do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 275, 40, 2, NULL, FALSE, NULL, NULL, 'endereco_pagador')
	, ('Bairro do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 315, 12, 2, NULL, FALSE, NULL, NULL, 'bairro_pagador')
	, ('Cep do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 327, 5, 1, NULL, FALSE, NULL, NULL, 'cep_pagador')
	, ('Sufixo do Cep do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 332, 3, 1, NULL, FALSE, NULL, NULL, 'sufixo_cep_pagador')
	, ('Cidade do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 335, 15, 2, NULL, FALSE, NULL, NULL, 'cidade_pagador')
	, ('Unidade de Federação do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 350, 2, 2, NULL, FALSE, NULL, NULL, 'uf_pagador')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 352, 30, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_3')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 382, 1, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_4')
	, ('Identificador do complemento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 383, 1, 2, NULL, FALSE, NULL, NULL, 'identificador_complemento')
	, ('Complemento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 384, 2, 1, NULL, FALSE, NULL, NULL, 'complemento')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 386, 6, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_5')
	, ('Número de dias corridos para Protesto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 392, 2, 1, NULL, FALSE, NULL, NULL, 'numero_dias_protesto')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 394, 1, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_6')
	, ('Número sequencial do registro no arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 3, 395, 6, 1, 3, FALSE, NULL, NULL, 'numero_sequencial_registro')
	-- TRAILER
	, ('Código do Registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 5, 1, 1, 1, NULL, FALSE, '9', NULL, 'codigo_registro')
	, ('Quantidade de registros', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 5, 2, 6, 1, NULL, FALSE, NULL, NULL, 'quantidade_registros')
	, ('Valor Total dos boletos', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 5, 8, 13, 1, NULL, FALSE, NULL, NULL, 'valor_total_boletos')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 5, 21, 374, 1, NULL, FALSE, NULL, NULL, 'reservado_banco')
	, ('Número sequencial de registro no arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_remessa' AND tipo_arquivo = 1 LIMIT 1), 5, 395, 6, 1, 3, FALSE, NULL, NULL, 'numero_sequencial_registro')

	-- ==============================================
	-- LAYOUT: cobranca_retorno
	-- ==============================================
	-- HEADER
	, ('Código do registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 1, 1, 1, NULL, FALSE, '0', NULL, 'codigo_registro')
	, ('Código da remessa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 2, 1, 1, NULL, FALSE, '2', NULL, 'codigo_remessa')
	, ('Literal de transmissão', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 3, 7, 2, NULL, FALSE, 'RETORNO', NULL, 'literal_transmissao')
	, ('Código de serviço', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 10, 2, 1, NULL, FALSE, '01', NULL, 'codigo_tipo_servico')
	, ('Literal do serviço', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 12, 15, 2, NULL, FALSE, 'COBRANCA       ', NULL, 'literal_servico')
	, ('Código da agência do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 27, 4, 1, NULL, FALSE, NULL, NULL, 'codigo_agencia_beneficiaria')
	, ('Conta Movimento do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 31, 8, 1, NULL, FALSE, NULL, NULL, 'conta_movimento_beneficiario')
	, ('Conta Cobrança do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 39, 8, 1, NULL, FALSE, NULL, NULL, 'conta_cobranca_beneficiario')
	, ('Código de Transmissão', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 27, 20, 1, 4, TRUE, NULL, NULL, 'codigo_transmissao')
	, ('Nome do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 47, 30, 2, 2, FALSE, NULL, NULL, 'nome_beneficiario')
	, ('Código do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 77, 3, 1, NULL, FALSE, NULL, NULL, 'codigo_banco')
	, ('Nome do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 80, 15, 2, NULL, FALSE, 'BRADESCO      ', NULL, 'nome_banco')
	, ('Data da geração do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 95, 6, 1, NULL, FALSE, NULL, NULL, 'data_geracao_arquivo')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 101, 8, 1, NULL, FALSE, '00000000', NULL, 'reservado_banco_1')
	, ('Código do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 109, 9, 1, NULL, FALSE, NULL, NULL, 'codigo_beneficiario')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 118, 268, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_2')
	, ('Sigla da empresa no sistema', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 386, 4, 2, NULL, FALSE, NULL, NULL, 'sigla_empresa_sistema')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 390, 2, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_3')
	, ('Número Sequência do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 392, 3, 1, NULL, FALSE, NULL, NULL, 'numero_sequencial_arquivo')
	, ('Número Sequencial do registro no arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 395, 6, 1, 3, FALSE, NULL, NULL, 'numero_sequencial_registro')
	-- MOVIMENTO
	, ('Código do Registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 1, 1, 1, NULL, FALSE, '1', NULL, 'codigo_registro')
	, ('Tipo de inscrição do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 2, 2, 1, NULL, FALSE, NULL, NULL, 'tipo_inscricao_beneficiario')
	, ('Inscrição do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 4, 14, 2, NULL, FALSE, NULL, NULL, 'inscricao_beneficiario')
	, ('Código de agência do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 18, 4, 1, NULL, FALSE, NULL, NULL, 'codigo_agencia_beneficiaria')
	, ('Conta movimento do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 22, 8, 1, NULL, FALSE, NULL, NULL, 'conta_movimento_beneficiario')
	, ('Conta cobrança do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 30, 8, 1, NULL, FALSE, NULL, NULL, 'conta_cobranca_beneficiario')
	, ('Identificação do boleto na empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 38, 25, 2, NULL, FALSE, NULL, NULL, 'identificacao_boleto_empresa')
	, ('Identificação do boleto no banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 63, 8, 1, NULL, FALSE, NULL, NULL, 'nosso_numero')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 71, 37, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_1')
	, ('Tipo de cobrança', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 108, 1, 1, NULL, FALSE, NULL, NULL, 'tipo_cobranca')
	, ('Código movimento retorno', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 109, 2, 1, NULL, FALSE, NULL, NULL, 'codigo_movimento_retorno')
	, ('Data da ocorrência', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 111, 6, 1, NULL, FALSE, NULL, NULL, 'data_ocorrencia')
	, ('Número do documento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 117, 10, 2, NULL, FALSE, NULL, NULL, 'numero_documento')
	, ('Identificação do boleto no banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 127, 8, 1, NULL, FALSE, NULL, NULL, 'nosso_numero_banco')
	, ('Código Original da remessa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 135, 2, 1, NULL, FALSE, NULL, NULL, 'codigo_original_remessa')
	, ('Código de erro/ocorrência (1º)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 137, 3, 2, NULL, FALSE, NULL, NULL, 'codigo_erro_ocorrencia_1')
	, ('Código de erro/ocorrência (2º)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 140, 3, 2, NULL, FALSE, NULL, NULL, 'codigo_erro_ocorrencia_2')
	, ('Código de erro/ocorrência (3º)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 143, 3, 2, NULL, FALSE, NULL, NULL, 'codigo_erro_ocorrencia_3')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 146, 1, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_2')
	, ('Data de vencimento do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 147, 6, 1, NULL, FALSE, NULL, NULL, 'data_vencimento_boleto')
	, ('Valor nominal do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 153, 13, 1, NULL, FALSE, NULL, NULL, 'valor_nominal_boleto')
	, ('Número do banco cobrador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 166, 3, 1, NULL, FALSE, NULL, NULL, 'numero_banco_cobrador')
	, ('Código da agência recebedora do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 169, 5, 1, NULL, FALSE, NULL, NULL, 'codigo_agencia_recebedora')
	, ('Espécie do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 174, 2, 1, NULL, FALSE, NULL, NULL, 'especie_boleto')
	, ('Valor da tarifa cobrada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 176, 13, 1, NULL, FALSE, NULL, NULL, 'valor_tarifa_cobrada')
	, ('Valor de outras despesas', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 189, 13, 1, NULL, FALSE, NULL, NULL, 'valor_outras_despesas')
	, ('Valor de juros de atraso', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 202, 13, 1, NULL, FALSE, NULL, NULL, 'valor_juros_atraso')
	, ('Valor de IOF recolhido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 215, 13, 1, NULL, FALSE, NULL, NULL, 'valor_iof_recolhido')
	, ('Valor do abatimento concedido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 228, 13, 1, NULL, FALSE, NULL, NULL, 'valor_abatimento')
	, ('Valor do desconto concedido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 241, 13, 1, NULL, FALSE, NULL, NULL, 'valor_desconto')
	, ('Valor total recebido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 254, 13, 1, NULL, FALSE, NULL, NULL, 'valor_total_recebido')
	, ('Valor do juros de mora', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 267, 13, 1, NULL, FALSE, NULL, NULL, 'valor_juros_mora')
	, ('Valor de outros créditos', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 280, 13, 1, NULL, FALSE, NULL, NULL, 'valor_outros_creditos')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 293, 1, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_3')
	, ('Identificação boleto aceite / não aceite', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 294, 1, 2, NULL, FALSE, NULL, NULL, 'identificacao_boleto_aceite')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 295, 1, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_4')
	, ('Data da efetivação crédito', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 296, 6, 1, NULL, FALSE, NULL, NULL, 'data_efetivacao_credito')
	, ('Nome do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 302, 36, 2, NULL, FALSE, NULL, NULL, 'nome_pagador')
	, ('Identificador do complemento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 338, 1, 2, NULL, FALSE, NULL, NULL, 'identificador_complemento')
	, ('Código da moeda', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 339, 2, 1, NULL, FALSE, NULL, NULL, 'codigo_moeda')
	, ('Valor do boleto em outra unidade', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 341, 13, 1, NULL, FALSE, NULL, NULL, 'valor_boleto_outra_unidade')
	, ('Valor do IOF em outra unidade', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 354, 13, 1, NULL, FALSE, NULL, NULL, 'valor_iof_outra_unidade')
	, ('Valor do débito ou crédito', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 367, 13, 1, NULL, FALSE, NULL, NULL, 'valor_debito_credito')
	, ('Identificação do lançamento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 380, 1, 2, NULL, FALSE, NULL, NULL, 'identificacao_lancamento')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 381, 3, 1, NULL, FALSE, NULL, NULL, 'reservado_banco_5')
	, ('Complemento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 384, 2, 1, NULL, FALSE, NULL, NULL, 'complemento')
	, ('Sigla da empresa no sistema', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 386, 4, 2, NULL, FALSE, NULL, NULL, 'sigla_empresa_sistema')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 390, 2, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_6')
	, ('Número Sequência do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 392, 3, 1, NULL, FALSE, NULL, NULL, 'numero_sequencial_arquivo')
	, ('Número Sequencial do registro no arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 395, 6, 1, 3, FALSE, NULL, NULL, 'numero_sequencial_registro')
	-- TRAILER
	, ('Código de registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 1, 1, 1, NULL, FALSE, '9', NULL, 'codigo_registro')
	, ('Código da remessa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 2, 1, 1, NULL, FALSE, '2', NULL, 'codigo_remessa')
	, ('Código do Serviço', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 3, 2, 1, NULL, FALSE, '01', NULL, 'codigo_tipo_servico')
	, ('Código do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 5, 3, 1, NULL, FALSE, NULL, NULL, 'codigo_banco')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 8, 10, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_1')
	, ('Quantidade de registros na cobrança Simples', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 18, 8, 1, NULL, FALSE, NULL, NULL, 'quantidade_registros_simples')
	, ('Valor total dos boletos na cobrança Simples', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 26, 12, 1, NULL, FALSE, NULL, NULL, 'valor_total_boletos_simples')
	, ('Número do aviso de cobrança Simples', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 40, 8, 1, NULL, FALSE, NULL, NULL, 'numero_aviso_cobranca_simples')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 48, 50, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_2')
	, ('Quantidade de registros na cobrança caucionada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 98, 8, 1, NULL, FALSE, NULL, NULL, 'quantidade_registros_caucionada')
	, ('Valor total dos boletos na cobrança caucionada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 106, 12, 1, NULL, FALSE, NULL, NULL, 'valor_total_boletos_caucionada')
	, ('Número do aviso da cobrança caucionada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 120, 8, 1, NULL, FALSE, NULL, NULL, 'numero_aviso_cobranca_caucionada')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 128, 10, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_3')
	, ('Quantidade de registros na cobrança descontada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 138, 8, 1, NULL, FALSE, NULL, NULL, 'quantidade_registros_descontada')
	, ('Valor total dos boletos na cobrança descontada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 146, 12, 1, NULL, FALSE, NULL, NULL, 'valor_total_boletos_descontada')
	, ('Número do aviso da cobrança descontada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 160, 8, 1, NULL, FALSE, NULL, NULL, 'numero_aviso_cobranca_descontada')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 168, 224, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_4')
	, ('Número Sequência do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 392, 3, 1, NULL, FALSE, NULL, NULL, 'numero_sequencial_arquivo')
	, ('Número Sequencial do registro do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_bradesco_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 395, 6, 1, 3, FALSE, NULL, NULL, 'numero_sequencial_registro')

	-- ==============================================
	-- LAYOUT: cobranca_santander_400_posicoes_retorno
	-- ==============================================
	-- HEADER
	, ('Código do registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 1, 1, 1, NULL, FALSE, '0', NULL, 'codigo_registro')
	, ('Código da remessa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 2, 1, 1, NULL, FALSE, '2', NULL, 'codigo_remessa')
	, ('Literal de transmissão', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 3, 7, 2, NULL, FALSE, 'RETORNO', NULL, 'literal_transmissao')
	, ('Código de serviço', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 10, 2, 1, NULL, FALSE, '01', NULL, 'codigo_tipo_servico')
	, ('Literal do serviço', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 12, 15, 2, NULL, FALSE, 'COBRANCA       ', NULL, 'literal_servico')
	, ('Código da agência do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 27, 4, 1, NULL, FALSE, NULL, NULL, 'codigo_agencia_beneficiaria')
	, ('Conta Movimento do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 31, 8, 1, NULL, FALSE, NULL, NULL, 'conta_movimento_beneficiario')
	, ('Conta Cobrança do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 39, 8, 1, NULL, FALSE, NULL, NULL, 'conta_cobranca_beneficiario')
	, ('Código de Transmissão', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 27, 20, 1, 4, TRUE, NULL, NULL, 'codigo_transmissao')
	, ('Nome do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 47, 30, 2, 2, FALSE, NULL, NULL, 'nome_beneficiario')
	, ('Código do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 77, 3, 1, NULL, FALSE, NULL, NULL, 'codigo_banco')
	, ('Nome do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 80, 15, 2, NULL, FALSE, 'SANTANDER     ', NULL, 'nome_banco')
	, ('Data da geração do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 95, 6, 1, NULL, FALSE, NULL, NULL, 'data_geracao_arquivo')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 101, 8, 1, NULL, FALSE, '00000000', NULL, 'reservado_banco_1')
	, ('Código do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 109, 9, 1, NULL, FALSE, NULL, NULL, 'codigo_beneficiario')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 118, 268, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_2')
	, ('Sigla da empresa no sistema', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 386, 4, 2, NULL, FALSE, NULL, NULL, 'sigla_empresa_sistema')
	, ('Reservado (uso banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 390, 2, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_3')
	, ('Número Sequência do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 392, 3, 1, NULL, FALSE, NULL, NULL, 'numero_sequencial_arquivo')
	, ('Número Sequencial do registro no arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 395, 6, 1, 3, FALSE, NULL, NULL, 'numero_sequencial_registro')
	-- MOVIMENTO
	, ('Código do Registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 1, 1, 1, NULL, FALSE, '1', NULL, 'codigo_registro')
	, ('Tipo de inscrição do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 2, 2, 1, NULL, FALSE, NULL, NULL, 'tipo_inscricao_beneficiario')
	, ('Inscrição do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 4, 14, 2, NULL, FALSE, NULL, NULL, 'inscricao_beneficiario')
	, ('Código de agência do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 18, 4, 1, NULL, FALSE, NULL, NULL, 'codigo_agencia_beneficiaria')
	, ('Conta movimento do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 22, 8, 1, NULL, FALSE, NULL, NULL, 'conta_movimento_beneficiario')
	, ('Conta cobrança do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 30, 8, 1, NULL, FALSE, NULL, NULL, 'conta_cobranca_beneficiario')
	, ('Identificação do boleto na empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 38, 25, 2, NULL, FALSE, NULL, NULL, 'identificacao_boleto_empresa')
	, ('Identificação do boleto no banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 63, 8, 1, NULL, FALSE, NULL, NULL, 'nosso_numero')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 71, 37, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_1')
	, ('Tipo de cobrança', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 108, 1, 1, NULL, FALSE, NULL, NULL, 'tipo_cobranca')
	, ('Código movimento retorno', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 109, 2, 1, NULL, FALSE, NULL, NULL, 'codigo_movimento_retorno')
	, ('Data da ocorrência', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 111, 6, 1, NULL, FALSE, NULL, NULL, 'data_ocorrencia')
	, ('Número do documento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 117, 10, 2, NULL, FALSE, NULL, NULL, 'numero_documento')
	, ('Identificação do boleto no banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 127, 8, 1, NULL, FALSE, NULL, NULL, 'nosso_numero_banco')
	, ('Código Original da remessa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 135, 2, 1, NULL, FALSE, NULL, NULL, 'codigo_original_remessa')
	, ('Código de erro/ocorrência (1º)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 137, 3, 2, NULL, FALSE, NULL, NULL, 'codigo_erro_ocorrencia_1')
	, ('Código de erro/ocorrência (2º)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 140, 3, 2, NULL, FALSE, NULL, NULL, 'codigo_erro_ocorrencia_2')
	, ('Código de erro/ocorrência (3º)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 143, 3, 2, NULL, FALSE, NULL, NULL, 'codigo_erro_ocorrencia_3')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 146, 1, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_2')
	, ('Data de vencimento do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 147, 6, 1, NULL, FALSE, NULL, NULL, 'data_vencimento_boleto')
	, ('Valor nominal do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 153, 13, 1, NULL, FALSE, NULL, NULL, 'valor_nominal_boleto')
	, ('Número do banco cobrador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 166, 3, 1, NULL, FALSE, NULL, NULL, 'numero_banco_cobrador')
	, ('Código da agência recebedora do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 169, 5, 1, NULL, FALSE, NULL, NULL, 'codigo_agencia_recebedora')
	, ('Espécie do boleto', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 174, 2, 1, NULL, FALSE, NULL, NULL, 'especie_boleto')
	, ('Valor da tarifa cobrada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 176, 13, 1, NULL, FALSE, NULL, NULL, 'valor_tarifa_cobrada')
	, ('Valor de outras despesas', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 189, 13, 1, NULL, FALSE, NULL, NULL, 'valor_outras_despesas')
	, ('Valor de juros de atraso', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 202, 13, 1, NULL, FALSE, NULL, NULL, 'valor_juros_atraso')
	, ('Valor de IOF recolhido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 215, 13, 1, NULL, FALSE, NULL, NULL, 'valor_iof_recolhido')
	, ('Valor do abatimento concedido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 228, 13, 1, NULL, FALSE, NULL, NULL, 'valor_abatimento')
	, ('Valor do desconto concedido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 241, 13, 1, NULL, FALSE, NULL, NULL, 'valor_desconto')
	, ('Valor total recebido', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 254, 13, 1, NULL, FALSE, NULL, NULL, 'valor_total_recebido')
	, ('Valor do juros de mora', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 267, 13, 1, NULL, FALSE, NULL, NULL, 'valor_juros_mora')
	, ('Valor de outros créditos', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 280, 13, 1, NULL, FALSE, NULL, NULL, 'valor_outros_creditos')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 293, 1, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_3')
	, ('Identificação boleto aceite / não aceite', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 294, 1, 2, NULL, FALSE, NULL, NULL, 'identificacao_boleto_aceite')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 295, 1, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_4')
	, ('Data da efetivação crédito', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 296, 6, 1, NULL, FALSE, NULL, NULL, 'data_efetivacao_credito')
	, ('Nome do Pagador', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 302, 36, 2, NULL, FALSE, NULL, NULL, 'nome_pagador')
	, ('Identificador do complemento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 338, 1, 2, NULL, FALSE, NULL, NULL, 'identificador_complemento')
	, ('Código da moeda', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 339, 2, 1, NULL, FALSE, NULL, NULL, 'codigo_moeda')
	, ('Valor do boleto em outra unidade', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 341, 13, 1, NULL, FALSE, NULL, NULL, 'valor_boleto_outra_unidade')
	, ('Valor do IOF em outra unidade', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 354, 13, 1, NULL, FALSE, NULL, NULL, 'valor_iof_outra_unidade')
	, ('Valor do débito ou crédito', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 367, 13, 1, NULL, FALSE, NULL, NULL, 'valor_debito_credito')
	, ('Identificação do lançamento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 380, 1, 2, NULL, FALSE, NULL, NULL, 'identificacao_lancamento')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 381, 3, 1, NULL, FALSE, NULL, NULL, 'reservado_banco_5')
	, ('Complemento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 384, 2, 1, NULL, FALSE, NULL, NULL, 'complemento')
	, ('Sigla da empresa no sistema', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 386, 4, 2, NULL, FALSE, NULL, NULL, 'sigla_empresa_sistema')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 390, 2, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_6')
	, ('Número Sequência do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 392, 3, 1, NULL, FALSE, NULL, NULL, 'numero_sequencial_arquivo')
	, ('Número Sequencial do registro no arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 3, 395, 6, 1, 3, FALSE, NULL, NULL, 'numero_sequencial_registro')
	-- TRAILER
	, ('Código de registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 1, 1, 1, NULL, FALSE, '9', NULL, 'codigo_registro')
	, ('Código da remessa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 2, 1, 1, NULL, FALSE, '2', NULL, 'codigo_remessa')
	, ('Código do Serviço', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 3, 2, 1, NULL, FALSE, '01', NULL, 'codigo_tipo_servico')
	, ('Código do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 5, 3, 1, NULL, FALSE, NULL, NULL, 'codigo_banco')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 8, 10, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_1')
	, ('Quantidade de registros na cobrança Simples', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 18, 8, 1, NULL, FALSE, NULL, NULL, 'quantidade_registros_simples')
	, ('Valor total dos boletos na cobrança Simples', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 26, 12, 1, NULL, FALSE, NULL, NULL, 'valor_total_boletos_simples')
	, ('Número do aviso de cobrança Simples', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 40, 8, 1, NULL, FALSE, NULL, NULL, 'numero_aviso_cobranca_simples')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 48, 50, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_2')
	, ('Quantidade de registros na cobrança caucionada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 98, 8, 1, NULL, FALSE, NULL, NULL, 'quantidade_registros_caucionada')
	, ('Valor total dos boletos na cobrança caucionada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 106, 12, 1, NULL, FALSE, NULL, NULL, 'valor_total_boletos_caucionada')
	, ('Número do aviso da cobrança caucionada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 120, 8, 1, NULL, FALSE, NULL, NULL, 'numero_aviso_cobranca_caucionada')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 128, 10, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_3')
	, ('Quantidade de registros na cobrança descontada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 138, 8, 1, NULL, FALSE, NULL, NULL, 'quantidade_registros_descontada')
	, ('Valor total dos boletos na cobrança descontada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 146, 12, 1, NULL, FALSE, NULL, NULL, 'valor_total_boletos_descontada')
	, ('Número do aviso da cobrança descontada', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 160, 8, 1, NULL, FALSE, NULL, NULL, 'numero_aviso_cobranca_descontada')
	, ('Reservado (uso Banco)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 168, 224, 2, NULL, FALSE, NULL, NULL, 'reservado_banco_4')
	, ('Número Sequência do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 392, 3, 1, NULL, FALSE, NULL, NULL, 'numero_sequencial_arquivo')
	, ('Número Sequencial do registro do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_santander_400_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 395, 6, 1, 3, FALSE, NULL, NULL, 'numero_sequencial_registro')
	-- ==============================================
	-- LAYOUT: cobranca_sicoob_240_posicoes_retorno
	-- ==============================================
	-- HEADER
	, ('Código do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 1, 3, 1, NULL, FALSE, '756', NULL, 'codigo_banco')
	, ('Código do registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 8, 1, 1, NULL, FALSE, '0', NULL, 'codigo_registro')
	, ('Código da transmissão', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 53, 20, 1, 4, TRUE, NULL, NULL, 'codigo_transmissao')
	, ('Nome do beneficiário', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 73, 30, 2, 2, FALSE, NULL, NULL, 'nome_beneficiario')
	, ('Nome do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 103, 30, 2, NULL, FALSE, 'SICOOB                        ', NULL, 'nome_banco')
	, ('Código de serviço (Retorno)', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 143, 1, 1, NULL, FALSE, '2', NULL, 'codigo_tipo_servico')
	, ('Data da geração do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 144, 8, 1, NULL, FALSE, NULL, NULL, 'data_geracao_arquivo')
	, ('Número sequencial do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 1, 158, 6, 1, NULL, FALSE, NULL, NULL, 'numero_sequencial_arquivo')
	-- TRAILER
	, ('Código do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 1, 3, 1, NULL, FALSE, '756', NULL, 'codigo_banco')
	, ('Código de registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 8, 1, 1, NULL, FALSE, '9', NULL, 'codigo_registro')
	, ('Quantidade de registros', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'cobranca_sicoob_240_posicoes_retorno' AND tipo_arquivo = 2 LIMIT 1), 5, 24, 6, 1, NULL, FALSE, NULL, NULL, 'quantidade_registros')
ON CONFLICT (id_leiaute_arquivo, tipo_campo, nome_coluna) DO UPDATE SET
	denominacao = EXCLUDED.denominacao
	, posicao_inicial = EXCLUDED.posicao_inicial
	, tamanho = EXCLUDED.tamanho
	, tipo_valor = EXCLUDED.tipo_valor
	, preenchimento = EXCLUDED.preenchimento
	, campo_identificacao = EXCLUDED.campo_identificacao
	, valor_padrao = EXCLUDED.valor_padrao
	, expressao_valor = EXCLUDED.expressao_valor;


-- =================================================================================
-- LEGACY / RASGUNHOS E EXEMPLOS DE CÓDIGO COMENTADOS
-- =================================================================================

/*
-- HEADER LOTE DRAFT
	('codigo do banco na compensacao', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 1, 3, 1, NULL, FALSE, '237')
	, ('lote de servico', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 4, 4, 1, NULL, FALSE, NULL)
	, ('tipo de registro', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 8, 1, 1, NULL, FALSE, '1')
	, ('tipo da operacao', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 9, 1, 2, NULL, FALSE, 'C')
	, ('tipo ddo servico', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 10, 2, 1, NULL, FALSE, NULL)
	, ('forma de lancamento', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 12, 2, 1, NULL, FALSE, NULL)
	, ('n da versao do layout do lote', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 14, 3, 1, NULL, FALSE, '040')
	, ('uso exclusivo da febraban', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 17, 1, 2, NULL, FALSE, ' ')
	, ('tipo de inscricao da empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 18, 1, 1, NULL, FALSE, NULL)
	, ('numero de inscricao da empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 19, 14, 1, 3, FALSE, NULL)
	, ('codigo do convenio no banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 33, 20, 2, NULL, FALSE, NULL)
	, ('agencia mantenedora da conta', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 53, 5, 1, 3, FALSE, NULL)
	, ('digito verificador da agencia', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 58, 1, 2, NULL, FALSE, NULL)
	, ('numero conta corrente', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 59, 12, 1, 3, FALSE, NULL)
	, ('digito verificador da conta corrente', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 71, 1, 2, NULL, FALSE, NULL)
	, ('digito verificador da agencia/conta', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 72, 1, 2, NULL, FALSE, NULL)
	, ('nome da empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 73, 30, 2, 2, FALSE, NULL)
	, ('mensagem', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 103, 40, 2, NULL, FALSE, NULL)
	, ('nome da rua, av, pca, etc', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 143, 30, 2, 2, FALSE, NULL)
--	, ('versao do layout do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 164, 3, 1, 3, FALSE, '080')
--	, ('densidade de gravacao do arquivo', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 167, 5, 1, 3, FALSE, NULL)
--	, ('para uso reservado do banco', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 172, 20, 2, NULL, FALSE, '                    ')
--	, ('para uso reservado da empresa', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 192, 20, 2, NULL, FALSE, '                    ')
--	, ('uso exclusivo febraban', (SELECT id FROM public.leiaute_arquivo WHERE denominacao = 'folha_pagamento_bradesco_240_posicoes' AND tipo_arquivo = 1 LIMIT 1), 2, 212, 29, 2, NULL, FALSE, '                             ');
*/

/*
INSERT INTO public.leiaute_arquivo (denominacao, tipo_arquivo, quantidade_caracteres, extensao_arquivo, versao_leiaute)
VALUES
	('folha_pagamento_240_posicoes', 1, 240, 2, '')
	, ('cobranca', 1, 400, 2, '')
	, ('multipag', 1, 240, 2, '');

INSERT INTO public.leiaute_campo_arquivo (id_leiaute_arquivo, tipo_campo, posicao_inicial, tamanho, tipo_valor, denominacao, campo_identificacao)
VALUES
	-- folha_pagamento_240_posicoes
	(1, 1, 001, 003, 1, 'codigo do banco -- g001', FALSE)
	, (1, 1, 004, 004, 1, 'lote de servico -- "0000" *g002', FALSE)
	, (1, 1, 008, 001, 1, 'tipo de registro -- "0" *g003', FALSE)
	, (1, 1, 009, 009, 2, 'uso exclusivo febraban -- brancos g004', FALSE)
	, (1, 1, 018, 001, 1, 'tipo de inscricao da empresa -- *g005', FALSE)
	, (1, 1, 019, 014, 1, 'numero de inscricao da empresa -- *g006', TRUE)
	, (1, 1, 033, 020, 2, 'codigo do convenio -- *g007', FALSE)
	, (1, 1, 053, 005, 1, 'conta corrente agencia codigo agencia mantenedora da conta -- *g008', FALSE)
	, (1, 1, 058, 001, 2, 'digito verificador da agencia -- *g009', FALSE)
	, (1, 1, 059, 012, 1, 'conta numero numero da conta corrente -- *g010', FALSE)
	, (1, 1, 071, 001, 2, 'digito verificador da conta -- *g011', FALSE)
	, (1, 1, 072, 001, 2, 'digito verificador da agencia conta -- *g012', FALSE)
	, (1, 1, 073, 030, 2, 'nome nome da empresa -- g013', FALSE)
	, (1, 1, 103, 030, 2, 'nome do banco nome do banco -- g014', FALSE)
	, (1, 1, 133, 010, 2, 'uso exclusivo febraban -- brancos g004', FALSE)
	, (1, 1, 143, 001, 1, 'arquivo codigo codigo remessa / retorno -- g015', FALSE)
	, (1, 1, 144, 008, 1, 'data de geracao do arquivo -- g016', FALSE)
	, (1, 1, 152, 006, 1, 'hora de geracao do arquivo -- g017', FALSE)
	, (1, 1, 158, 006, 1, 'numero sequencial do arquivo -- *g018', FALSE)
	, (1, 1, 164, 003, 1, 'versao do layout do arquivo -- "080" *g019', FALSE)
	, (1, 1, 167, 005, 1, 'densidade de gravacao do arquivo -- g020', FALSE)
	, (1, 1, 172, 020, 2, 'para uso reservado do banco -- g021', FALSE)
	, (1, 1, 192, 020, 2, 'para uso reservado da empresa -- g022', FALSE)
	, (1, 1, 212, 029, 2, 'uso exclusivo febraban -- brancos g004', FALSE)
	-- cobranca
	, (2, 1, 001, 001, 1, 'tipo de registro -- 0', FALSE)
	, (2, 1, 002, 001, 1, 'identificacao do arquivo-remessa -- 1', FALSE)
	, (2, 1, 003, 007, 1, 'literal remessa -- remessa', FALSE)
	, (2, 1, 010, 002, 1, 'codigo de servico -- 01', FALSE)
	, (2, 1, 012, 015, 1, 'literal servico -- cobranca', FALSE)
	, (2, 1, 027, 020, 1, 'codigo do convenio -- será fornecido pelo bradesco, quando do cadastramento', TRUE)
	, (2, 1, 047, 030, 1, 'nome da empresa -- razao social', FALSE)
	, (2, 1, 077, 003, 1, 'codigo do banco -- 237', FALSE)
	, (2, 1, 080, 015, 1, 'nome do banco -- bradesco', FALSE)
	, (2, 1, 095, 006, 1, 'data da gravacao do arquivo -- ddmmaa', FALSE)
	, (2, 1, 101, 008, 1, 'branco -- branco', FALSE)
	, (2, 1, 109, 002, 1, 'identificacao do sistema -- mx', FALSE)
	, (2, 1, 111, 007, 1, 'numero sequencial do arquivo -- sequencial', FALSE)
	, (2, 1, 118, 277, 1, 'branco -- branco', FALSE)
	, (2, 1, 395, 006, 1, 'numero sequencial do registro de um em um -- 000001', FALSE)
	-- multipag
	, (3, 1, 001, 003, 1, 'codigo do banco -- g001', FALSE)
	, (3, 1, 004, 004, 1, 'lote de servico -- "0000" *g002', FALSE)
	, (3, 1, 008, 001, 1, 'tipo de registro -- "0" *g003', FALSE)
	, (3, 1, 009, 009, 2, 'uso exclusivo febraban -- brancos g004', FALSE)
	, (3, 1, 018, 001, 1, 'tipo de inscricao da empresa -- *g005', FALSE)
	, (3, 1, 019, 014, 1, 'numero de inscricao da empresa -- *g006', TRUE)
	, (3, 1, 033, 020, 2, 'codigo do convenio -- *g007', FALSE)
	, (3, 1, 053, 005, 1, 'conta corrente agencia codigo agencia mantenedora da conta -- *g008', FALSE)
	, (3, 1, 058, 001, 2, 'digito verificador da agencia -- *g009', FALSE)
	, (3, 1, 059, 012, 1, 'conta numero numero da conta corrente -- *g010', FALSE)
	, (3, 1, 071, 001, 2, 'digito verificador da conta -- *g011', FALSE)
	, (3, 1, 072, 001, 2, 'digito verificador da agencia conta -- *g012', FALSE)
	, (3, 1, 073, 030, 2, 'nome nome da empresa -- g013', FALSE)
	, (3, 1, 103, 030, 2, 'nome do banco nome do banco -- g014', FALSE)
	, (3, 1, 133, 010, 2, 'uso exclusivo febraban -- brancos g004', FALSE)
	, (3, 1, 143, 001, 1, 'arquivo codigo codigo remessa / retorno -- g015', FALSE)
	, (3, 1, 144, 008, 1, 'data de geracao do arquivo -- g016', FALSE)
	, (3, 1, 152, 006, 1, 'hora de geracao do arquivo -- g017', FALSE)
	, (3, 1, 158, 006, 1, 'numero sequencial do arquivo -- *g018', FALSE)
	, (3, 1, 164, 003, 1, 'versao do layout do arquivo -- "089" *g019', FALSE)
	, (3, 1, 167, 005, 1, 'densidade de gravacao do arquivo -- g020', FALSE)
	, (3, 1, 172, 020, 2, 'para uso reservado do banco -- g021', FALSE)
	, (3, 1, 192, 020, 2, 'para uso reservado da empresa -- g022', FALSE)
	, (3, 1, 212, 029, 2, 'uso exclusivo febraban -- brancos g004', FALSE);
*/